language: elixir
elixir:
  - 1.5
  - 1.4
otp_release:
  - 19.0
env:
  -
  - UUID=resource_owners
  - UUID=all
sudo: false
matrix:
  exclude:
    - elixir: 1.4
      env: UUID=resource_owners
    - elixir: 1.4
      env: UUID=all
script:
  - mix test
after_script:
  - mix credo
