language: elixir
sudo: false
matrix:
  include:
    - elixir: 1.8
      otp_release: 21.0
      env: MIX_ENV=test
    - elixir: 1.8
      otp_release: 21.0
      env: MIX_ENV=test UUID=true
script:
  - mix test
after_script:
  - mix credo
