language: elixir
env:
  - MIX_ENV=test
  - UUID=resource_owners MIX_ENV=test
  - UUID=all MIX_ENV=test
sudo: false
matrix:
  include:
    - elixir: 1.4
      otp_release: 19.0
    - elixir: 1.5
      otp_release: 19.0
    - elixir: 1.6
      otp_release: 20.0
    - elixir: 1.7
      otp_release: 20.0
      env: UUID=resource_owners MIX_ENV=test
    - elixir: 1.7
      otp_release: 20.0
      env: UUID=all MIX_ENV=test
script:
  - mix deps.compile
  - mix test
after_script:
  - mix credo
