language: elixir
elixir:
  - 1.5
  - 1.4
otp_release:
  - 19.0
script:
  - mix deps.compile
  - mix test
  - mix credo

  - rm -rf _build
  - UUID=resource_owners mix test

  - rm -rf _build
  - UUID=all mix test

env:
  - MIX_ENV=test
